### ISSUE TITLE
Errors...

### ISSUE THREAD

**Issue by Srg-Batman** [brandon15811/Minecraft-PE-Proxy#2]
Hi I'm setting up this on one of my Developers laptop (32Bit) and I get this error everytime I do node mcpeproxy.js --serverip "IP" and node mcpeproxy.js 

Error code: 

!!!!!!TYPE node mcpeproxy.js!!!!!!
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\X60\Desktop\Minecraft-PE-Proxy-master>node mcpeproxy.js
   info  - socket.io started
[INFO]: Proxy listening on port: 19133
[INFO]: Forwarding packets to: 67.176.50.101:19135

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EINVAL
    at errnoException (dgram.js:439:11)
    at dgram.js:206:28
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:903:3

He says He can't see servers on his end.
Please get back to me soon as possible. 
I really need him to test a few things.

**Comment by brandon15811** [comment]
Sorry for such a late response, been really busy with school lately
But usually EINVAL indicates that the port is already in use, try using --proxyPort to use a different port (somewhere between 19132 and 19135)

**Comment by Srg-Batman** [comment]
Actually it was just Node.js that was the problem 

Sent via my Samsung Transform™ Ultra from Boost Mobile

brandon15811 notifications@github.com wrote:

Sorry for such a late response, been really busy with school lately
But usually EINVAL indicates that the port is already in use, try using --proxyPort to use a different port (somewhere between 19132 and 19135)

**Comment by brandon15811** [comment]
Can you come to irc and I'll help you out there? http://webchat.freenode.net/?channels=mcpedevs&uio=d4

**Comment by shoghicp** [comment]
Is this fixed xD?

**Comment by brandon15811** [comment]
@shoghicp it should be, I develop on 0.10 now xD
@Srg-Batman can you check?
