### ISSUE TITLE
Multiple IP Bind

### ISSUE THREAD

**Issue by rj0495** [brandon15811/Minecraft-PE-Proxy#4]
Can you add a way to use another IP address like a Web proxy?

**Comment by williamtdr** [comment]
This isn't really under active development, and it'd probably be rewritten if needed (not speaking for Brandon) - there are lots of memory leaks and it can't support many players for the amount of hardware thrown at it.

**Comment by rj0495** [comment]
Well do you know any alternatives?

**Comment by rj0495** [comment]
@williamtdr

**Comment by williamtdr** [comment]
@rj0495 I have a slightly modified fork in my repos with mutlithreading, but again, huge memory leaks. You could wait for the official Pocketmine Rubberband proxy.

**Comment by rj0495** [comment]
How long will that be?
